// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using praesentationsanmeldung.Data;

#nullable disable

namespace praesentationsanmeldung.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("praesentationsanmeldung.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Eintragung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EingetragenAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("G3SusId")
                        .HasColumnType("int");

                    b.Property<int>("PraesentationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PraesentationId");

                    b.HasIndex("G3SusId", "PraesentationId")
                        .IsUnique();

                    b.ToTable("Eintragungen");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.G3Sus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Klasse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("G3Sus");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Praesentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Beginn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RaumId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RaumId");

                    b.ToTable("Praesentationen");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Raum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Kapazitaet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Bezeichnung")
                        .IsUnique();

                    b.ToTable("Raeume");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Eintragung", b =>
                {
                    b.HasOne("praesentationsanmeldung.Models.G3Sus", "G3Sus")
                        .WithMany("Eintragungen")
                        .HasForeignKey("G3SusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praesentationsanmeldung.Models.Praesentation", "Praesentation")
                        .WithMany("Eintragungen")
                        .HasForeignKey("PraesentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("G3Sus");

                    b.Navigation("Praesentation");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Praesentation", b =>
                {
                    b.HasOne("praesentationsanmeldung.Models.Raum", "Raum")
                        .WithMany("Praesentationen")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raum");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.G3Sus", b =>
                {
                    b.Navigation("Eintragungen");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Praesentation", b =>
                {
                    b.Navigation("Eintragungen");
                });

            modelBuilder.Entity("praesentationsanmeldung.Models.Raum", b =>
                {
                    b.Navigation("Praesentationen");
                });
#pragma warning restore 612, 618
        }
    }
}
